import pytest
from src.mcp_tools.cyclomatic import ComplexityAnalyzer

def test_complexity_reduction_success():
    """Test that simplifying code correctly calculates Delta D > 0."""
    spaghetti = "def f():\n if True:\n  if True:\n   pass"
    clean = "def f():\n pass"
    
    result = ComplexityAnalyzer.evaluate_debt_reduction(spaghetti, clean)
    
    assert result["success"] is True
    assert result["is_improved"] is True
    assert result["delta_d"] > 0

def test_syntax_error_handling():
    """Test that the tool catches syntax errors generated by hallucinating LLMs."""
    bad_code = "def f() if True pass" # Missing colons, bad syntax
    clean_code = "def f(): pass"
    
    result = ComplexityAnalyzer.evaluate_debt_reduction(bad_code, clean_code)
    assert result["success"] is False
    assert "SyntaxError" in result["error"]